//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int Id { get; set; }
        public string CityName { get; set; }
        public string CountryCode2 { get; set; }
        public string State { get; set; }
        public int TouristRating { get; set; }
        public System.DateTime DateEstablished { get; set; }
        public int Population { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
