//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eventsappEntities : DbContext
    {
        public eventsappEntities()
            : base("name=eventsappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoggedUserConnection> LoggedUserConnections { get; set; }
        public virtual DbSet<PreferredLanguage> PreferredLanguages { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserActionsTaken> UserActionsTakens { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserCompany> UserCompanies { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<IOSDevice> IOSDevices { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Agendum> Agenda { get; set; }
        public virtual DbSet<AgendaSession> AgendaSessions { get; set; }
        public virtual DbSet<AthleteVoucher> AthleteVouchers { get; set; }
        public virtual DbSet<AttendeeQuestion> AttendeeQuestions { get; set; }
        public virtual DbSet<ClaimedVoucher> ClaimedVouchers { get; set; }
        public virtual DbSet<EventAddress> EventAddresses { get; set; }
        public virtual DbSet<EventCompany> EventCompanies { get; set; }
        public virtual DbSet<EventNew> EventNews { get; set; }
        public virtual DbSet<EventPerson> EventPersons { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventUser> EventUsers { get; set; }
        public virtual DbSet<GuestVoucher> GuestVouchers { get; set; }
        public virtual DbSet<InterestedAgenda> InterestedAgendas { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Presentation> Presentations { get; set; }
        public virtual DbSet<SpeakerRating> SpeakerRatings { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<SurveyOption> SurveyOptions { get; set; }
        public virtual DbSet<SurveyResult> SurveyResults { get; set; }
        public virtual DbSet<BackgroundTheme> BackgroundThemes { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EventPackage> EventPackages { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<ParticipantsRegistrationType> ParticipantsRegistrationTypes { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatuses { get; set; }
        public virtual DbSet<PersonType> PersonTypes { get; set; }
        public virtual DbSet<RegistrationType> RegistrationTypes { get; set; }
        public virtual DbSet<SponserType> SponserTypes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserAction> UserActions { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<PushNotification> PushNotifications { get; set; }
        public virtual DbSet<Recipient> Recipients { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserSubscription> UserSubscriptions { get; set; }
    
        public virtual int AddUserRole(Nullable<int> userId, Nullable<int> roleId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUserRole", userIdParameter, roleIdParameter);
        }
    
        [DbFunction("eventsappEntities", "fn_GetRegisteredUsers")]
        public virtual IQueryable<fn_GetRegisteredUsers_Result> fn_GetRegisteredUsers(Nullable<int> eventId, Nullable<int> userId, Nullable<int> roleId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_GetRegisteredUsers_Result>("[eventsappEntities].[fn_GetRegisteredUsers](@EventId, @userId, @roleId)", eventIdParameter, userIdParameter, roleIdParameter);
        }
    
        [DbFunction("eventsappEntities", "fn_GetSurveyResult")]
        public virtual IQueryable<fn_GetSurveyResult_Result> fn_GetSurveyResult(Nullable<int> eventId, Nullable<int> userId, Nullable<int> roleId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_GetSurveyResult_Result>("[eventsappEntities].[fn_GetSurveyResult](@EventId, @userId, @roleId)", eventIdParameter, userIdParameter, roleIdParameter);
        }
    
        [DbFunction("eventsappEntities", "fn_GetUsersAttendance")]
        public virtual IQueryable<fn_GetUsersAttendance_Result> fn_GetUsersAttendance(Nullable<int> eventId, Nullable<int> userId, Nullable<int> roleId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_GetUsersAttendance_Result>("[eventsappEntities].[fn_GetUsersAttendance](@EventId, @userId, @roleId)", eventIdParameter, userIdParameter, roleIdParameter);
        }
    
        public virtual int InsertBulkResponses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertBulkResponses");
        }
    
        public virtual int InsertBulkUserforEvents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertBulkUserforEvents");
        }
    
        public virtual ObjectResult<UserAttendHistory_Result> UserAttendHistory(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserAttendHistory_Result>("UserAttendHistory", userIdParameter);
        }
    }
}
