//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventUser
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int EventId { get; set; }
        public Nullable<bool> IsAttended { get; set; }
        public Nullable<int> RegistrationTypeId { get; set; }
        public string QRCode { get; set; }
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> UserSubscriptionId { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public Nullable<int> AgendaId { get; set; }
        public Nullable<bool> IsIndividual { get; set; }
        public Nullable<int> VisitorCount { get; set; }
    
        public virtual User User { get; set; }
        public virtual Agendum Agendum { get; set; }
        public virtual Event Event { get; set; }
        public virtual RegistrationType RegistrationType { get; set; }
        public virtual UserSubscription UserSubscription { get; set; }
    }
}
