//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCompany
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int EventId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string StandLocation { get; set; }
        public string StandNumber { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> CompanyTypeId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        public virtual Package Package { get; set; }
        public virtual Event Event { get; set; }
    }
}
