//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
