//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.EventCompanies = new HashSet<EventCompany>();
        }
    
        public int Id { get; set; }
        public string Benefits { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> SponsorTypeId { get; set; }
        public Nullable<int> EventId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventCompany> EventCompanies { get; set; }
        public virtual Event Event { get; set; }
        public virtual SponserType SponserType { get; set; }
    }
}
