//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Id { get; set; }
        public string PhotoName { get; set; }
        public int EventId { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string DescEn { get; set; }
        public string DescAr { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
