//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        public int Id { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public string ReferenceConnectionId { get; set; }
        public int NotificationId { get; set; }
        public Nullable<bool> IsSent { get; set; }
    
        public virtual PushNotification PushNotification { get; set; }
    }
}
