//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResult
    {
        public int Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int SurveyOptionId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<int> AgendaId { get; set; }
        public Nullable<int> EventId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Agendum Agendum { get; set; }
        public virtual Event Event { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual SurveyOption SurveyOption { get; set; }
        public virtual SurveyResult SurveyResults1 { get; set; }
        public virtual SurveyResult SurveyResult1 { get; set; }
    }
}
