//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.SurveyOptions = new HashSet<SurveyOption>();
            this.SurveyResults = new HashSet<SurveyResult>();
        }
    
        public int Id { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public int EventId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> AgendaId { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> FromSpeaker { get; set; }
        public Nullable<int> ResponseAlotTime { get; set; }
    
        public virtual Agendum Agendum { get; set; }
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyOption> SurveyOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyResult> SurveyResults { get; set; }
    }
}
