//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.UserSubscriptions = new HashSet<UserSubscription>();
        }
    
        public int Id { get; set; }
        public string cartId { get; set; }
        public string test { get; set; }
        public string amount { get; set; }
        public string currency { get; set; }
        public string reference { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public string paymentref { get; set; }
        public string email { get; set; }
        public string forenames { get; set; }
        public string surname { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string line1 { get; set; }
        public string authorisedURL { get; set; }
        public string statusCode { get; set; }
        public string statusText { get; set; }
        public Nullable<int> UserSubscriptionId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserSubscription UserSubscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSubscription> UserSubscriptions { get; set; }
    }
}
